### ISSUE TITLE
Can not load Simpl program..

### ISSUE THREAD

**Issue by micdre** [ProfessorAire/ElegantXML-Crestron#9]
Hi Professor Aire,

First of all, thanks for the VS files/programs. Learned a lot of them!

When i try to load the Simpl file, any of them, i get a "Invalid file signature, extension, acess rights.....etc" error.
Can not resolve this. Tried other naming, rights etc.
Are you familiar with this?

Kind regards, Michel

**Comment by ProfessorAire** [comment]
@micdre First off, sorry for the late response, I just saw your post on Discord.

I just confirmed that when downloading the source directly the files are downloaded with simple LF endings instead of Windows CRLF endings. This will prevent the SMW files from opening. If you need to use the source you can either do a search and replace to substitute LF with CRLF, or you can clone the repo directly, which should renormalize the line endings.

I'll do my best to revisit this when I have some time to configure git to not renormalize the line endings on commit and to recommit the repo with correct line endings.

**Comment by micdre** [comment]
Hi,

Thanks for you reply! Appriciate that.
What do you mean with  'clone the repo'?

Regards,  Michel

⁣Verzonden door BlueMail ​

Op 23 okt. 2020 16:06, om 16:06, Christopher McNeely <notifications@github.com> schreef:

**Comment by ProfessorAire** [comment]
@micdre When you select the Code dropdown on the root of the Github repository you have the ability to select a variety of options. (See image below.) If you copy the git address (https://github.com/ProfessorAire/ElegantXML-Crestron.git) you can clone the repo, either using a Git client (like Github Desktop) or through the command line, with the command `git clone https://github.com/ProfessorAire/ElegantXML-Crestron.git`. This will clone the repository, which pulls the data all down to your local in a state ready for editing.

Please be aware that the sample files are all built using 'release' versions of the modules, which are created through an application I use locally, and thus the programs won't open unless the correct versions of the modules are used. You can download those by downloading the latest release from the [releases page](https://github.com/ProfessorAire/ElegantXML-Crestron/releases).

![image](https://user-images.githubusercontent.com/22963406/97253774-3c740080-17ca-11eb-9046-eb757ef37b94.png)

**Comment by micdre** [comment]
Now i'm sorry for a late reaction! Thanks for your kind explanation. Gonna try this.

Kind regards, Michel

**Comment by micdre** [comment]
Get your Sample file to work but now i want  to load the XML file from a server location. 
I don't know where top begin.....can you gave me a start? 
I'm asking much, I know. Just trieing to get my head around it.

Kind Regards, Michel

**Comment by ProfessorAire** [comment]
As long as the server hosting the file is doing so without authentication requirements this should be pretty easy. I would recommend looking in the `Crestron.SimplSharp.Net.Http` or `Crestron.SimplSharp.Net.Https` namespaces for what you'll need to do this.
